version: '3'

services:
  api:
    container_name: "follower-api"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8001:8080
    environment:
      DB_USER: sa
      DB_PASSWORD: password
      DB_NAME: compose-db
      DB_HOST: postgres_db
      DB_PORT: 5432

  db:
    container_name: follower_db
    image: postgres:12
    ports:
      - 5435:5432
    environment:
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: password
      POSTGRES_DB: compose-db
    volumes:
      - followerdata:/var/lib/postgresql/data

volumes:
  pgdata:
    external: false